# permissions for end users to view logstashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logstash-viewer-role
rules:
- apiGroups:
  - logstash.vkiedrowski.de
  resources:
  - logstashes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logstash.vkiedrowski.de
  resources:
  - logstashes/status
  verbs:
  - get
