
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logstash.vkiedrowski.de
  resources:
  - logstashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logstash.vkiedrowski.de
  resources:
  - logstashes/finalizers
  verbs:
  - update
- apiGroups:
  - logstash.vkiedrowski.de
  resources:
  - logstashes/status
  verbs:
  - get
  - patch
  - update
