## Append samples you want in your CSV to this file as resources ##
resources:
- logstash_v1alpha1_logstash.yaml
- logstash.vkiedrowski.de_logstashpipeline.yaml
- logstash.vkiedrowski.de_logstashoutputs.yaml
- logstash.vkiedrowski.de_logstashinputs.yaml
- logstash.vkiedrowski.de_logstashfilters.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
