apiVersion: logstash.vkiedrowski.de/v1alpha1
kind: LogstashPipeline
metadata:
  name: pipeline-sample1
spec:
  selector: vkiedrowski.de/pipeline in (pipeline1)
  config: |
    input {
      beats {
        port => 5045
      }
    }
    output {
      stdout { codec => rubydebug }
    }
---
apiVersion: logstash.vkiedrowski.de/v1alpha1
kind: LogstashPipeline
metadata:
  name: pipeline-sample2
spec:
  selector: vkiedrowski.de/pipeline in (pipeline2)
  config: |
    input {
      beats {
        port => 5046
      }
    }
    output {
      stdout { codec => rubydebug }
    }