apiVersion: logstash.vkiedrowski.de/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  # Add fields here
  replicaCount: 1
  pipelines:
    - pipeline-sample1
  storage:
    storageClassName: local-path
